name: avantspace_mobile_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.1+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.2
  camera: ^0.9.4+21
  flutter_svg: ^1.0.3
  share_plus: ^4.0.4
  fluttertoast: ^8.0.9
  gallery_saver: ^2.3.2
  permission_handler: ^9.2.0
  google_maps_flutter: ^2.1.3
  location: ^4.3.0
  video_player: ^2.4.0
  flutter_compass: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true
  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
  assets:
   - assets/images/
   - assets/images/flags/
   - assets/images/bottom_navigation_panel/
   - assets/fonts/