name: avantspace_mobile_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.1+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.3
  camera: ^0.10.0+1
  flutter_svg: ^1.1.5
  share_plus: ^4.1.0
  gallery_saver: ^2.3.2
  permission_handler: ^10.0.0
  google_maps_flutter: ^2.2.0
  location: ^4.4.0
  flutter_compass: ^0.7.0

dev_dependencies:
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
  assets:
   - assets/images/
   - assets/images/flags/
   - assets/images/bottom_navigation_panel/
   - assets/fonts/